export interface MerchantRule {
  name: string;
  isEligible: boolean;
  mcc?: string;
}

export const MERCHANT_OVERRIDES: Record<string, boolean> = {
  // --- 8.88% ELIGIBLE ---
  'baba accessories': true,
  'pal': true,
  'philippine airlines': true,
  'cebu pacific': true,
  'eva airways': true,
  'cathay pacific': true,
  'malaysia airlines': true,
  'shangri-la': true,
  'agoda': true,
  'airasia': true,
  'airbnb': true,
  'booking.com': true,
  'google': true,
  'utilities': true,
  'dito': true,
  'gigalife': true,
  'globe': true,
  'gomo': true,
  'pldt': true,
  'smart': true,
  'starlink': true,
  'zoom': true,
  'dropbox': true,
  'wise': true,
  'cignal': true,
  'netflix': true,
  'royal cable': true,
  'sky cable': true,
  'bayad': true,
  'converge': true,
  'manila water': true,
  'meralco': true,
  'unioil': true,
  'sm store': true,
  'rustans': true,
  'shopsm': true,
  'landmark': true,
  'isetann': true,
  'alibaba': true,
  'amazon': true,
  'ebay': true,
  'elev8 fitness': true,
  'lazada': true,
  'shopee': true,
  'pick.a.roo': true,
  'robinson\'s dept. store': true,
  'robinsons department store': true,
  'caltex': true,
  'shell': true,
  'petron': true,
  'infinity spa': true,
  'net-a-porter': true,
  'shein': true,
  'surplus': true,
  'zara': true,
  'lululemon': true,
  'skechers': true,
  'nike': true,
  'cln': true,
  'celine': true,
  'dior': true,
  'prada': true,
  'projekt 8': true,
  'bottega veneta': true,
  'marks & spencer': true,
  'trunc ph': true,
  'zalora': true,
  'bench': true,
  'gucci': true,
  'hermes': true,
  'penguin': true,
  'mi store': true,
  'dyson': true,
  'octagon': true,
  'razer': true,
  'aa bbq': true,
  'boy belly': true,

  'boy belly': true,
  'contis': true,
  'starbucks': true,
  'jollibee': true,
  'mcdo': true,
  'kfc': true,
  'chowking': true,
  'foodpanda': true,
  'grab food': true,
  'grab mart': true,
  'greenwich': true,
  'mang inasal': true,
  'max\'s': true,
  'shakeys': true,
  'red ribbon': true,
  'ramen nagi': true,
  'coffee bean': true,
  'army navy': true,
  'bonchon': true,
  'kenny rogers': true,
  'llaollao': true,
  'mamou': true,
  'manam': true,
  'nanyang': true,
  'zus coffee': true,
  'chili\'s': true,
  'texas roadhouse': true,
  'angel\'s pizza online': true,
  'tokyo tokyo': true,
  'vikings': true,
  'yabu': true,
  'yakimix': true,
  'yayoi': true,
  'yoshinoya': true,
  'baby central': true,
  'miniso': true,
  'klook': true,
  'sheraton': true,
  'sogo': true,

  // --- 0.30% INELIGIBLE (Explicit Exclusions) ---
  'vets unlimited': false,
  'angkas': false,
  'green gsm': false,
  'grab': false, // General Grab (includes Grab Car/Transport) is 0.30%
  'burger king': false,
  'coco ichibanya': false,
  'french baker': false,
  'angel\'s pizza in-store': false,
  'autosweep': false,
  'smc skyway': false,
  'ace hardware': false,
  'mandaue foam': false,
  'the diy shop': false,
  'handyman': false,
  'true value': false,
  'mr diy': false,
  'sukigrocer': false,
  'tiktok shop': false,
  'myeg': false,
  'heyday': false,
  'puregold': false,
  'robinsons easymart': false,
  'robinsons supermarket': false,
  'dali': false,
  'kemp mart': false,
  'gl delmonte': false,
  'come n shop': false,
  'savemore': false,
  'landers': false,
  'merkado': false,
  'shopwise': false,
  'cash & carry': false,
  'restaurant depot': false,
  'healthy options': false,
  's&r': false,
  'the marketplace': false,
  'santis': false,
  'cinnabon': false,
  'equilibrium intertrade': false,
  'lawson': false,
  'chatime': false,
  'royce chocolates': false,
  'saree': false,
  'super50': false,
  'salad stop': false,
  'hamleys': false,
  'penshoppe': false,
  'uniqlo': false,
  'ikea': false,
  'abenson': false,
  'samsung': false,
  'bitwarden': false,
  'datablitz': false,
  'lista app': false,
  'spotify': false,
  'youtube premium': false,
  'envato': false,
  'airalo': false,
  'openai': false,
  'chatgpt': false,
  'google play': false,
  'merrymart': false,
  'mercury drug': false,
  'watsons': false,
  'southstar drug': false,
  'adidas': false,
  'decathlon': false,
  'olympic village': false,
  'toby\'s': false,
  'under armour': false,
  'national book store': false,
  'pandayan': false,
  'office warehouse': false,
  'cartier': false,
  'sincere watch': false,
  'swiss gallery': false,
  'japan home': false,
  'anello': false,
  'rimowa': false,
  'tumi': false,
  'megasaver': false,
  'pet express': false,
  'insurance': false,
  'manulife': false,
  'prulife': false,
  'sunlife': false,
  'grab cash in': false,
  'maya cash in': false,
  'linkedin': false,
  'facebook ads': false,
  'anytime fitness': false,
  'tax': false,
  'government': false,
  'myeg': false,
  'sm ticket': false,
};

export type MerchantStatus = 'eligible' | 'exclusion' | 'unlisted';

export function getMerchantStatus(merchantName: string, category: string): MerchantStatus {
  if (!merchantName) return 'unlisted';
  const normalized = merchantName.toLowerCase();
  
  // 1. Check explicit overrides first (Verified Data)
  for (const [key, eligible] of Object.entries(MERCHANT_OVERRIDES)) {
    if (normalized.includes(key)) {
      return eligible ? 'eligible' : 'exclusion';
    }
  }

  // 2. If not in the list, we can still guess based on category for the calculation,
  // but for the UI we want to flag it as unlisted.
  return 'unlisted';
}

// Keep the boolean version for the actual math calculations
export function checkMerchantEligibility(merchantName: string, category: string): boolean {
  const status = getMerchantStatus(merchantName, category);
  if (status === 'eligible') return true;
  if (status === 'exclusion') return false;

  // Fallback to Category Logic for unlisted stores
  const eligibleCategories = ['dining', 'groceries', 'travel', 'fuel', 'utilities'];
  return eligibleCategories.includes(category.toLowerCase());
}
